---
title: "CV Leduc"
output: html_document
date: '2024-07-18'
---
# SGD GMF

```{r}
library(here)
library(sgdGMF)
library(dplyr)
library(RSpectra)
library(scater)
library(BiocParallel)
library(BiocSingular)
library(DelayedArray)
library(fullRankMatrix)

devtools::load_all(here("omicsGMF"))

```

# Load data
```{r}
sce <- readRDS(file = here("Data","leduc2022_pSCoPE_data","leduc_sce.RDS"))

```


## Cross validation

```{r}
set.seed(100)



design <- model.matrix(~1+Channel+Set, data = colData(sce))
fmX <- make_full_rank_matrix(design)
X <- fmX$matrix

dim(sce)
family <- gaussian()
cv <- calculateCVGMF(sce, family = family, X = X, 
                      exprs_values = "logintensities", ncomponents = c(seq(1,20,1), seq(25,50,5)), 
                      control.alg = list(tol = 0.001, maxiter = 10000), 
                      control.cv = list(nfolds = 3),
                      ntop = nrow(sce))
saveRDS(object = cv, file = here("Analyses","Leduc","Output","crossval_batch.RDS"))

```
```{r}
print(cv)
print(cv %>% group_by(ncomp) %>% summarise(mean_dev = mean(dev)))

```





