---
title: "Untitled"
output: html_document
date: '2024-07-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(nipals)
library(here)
library(scran)
library(SummarizedExperiment)
library(SingleCellExperiment)
```

```{r}
set.seed(100)
sce <- readRDS(file = here("Analyses","Leduc","Output_batch_effect_removal","logintensities_batch_removed.RDS"))
data <- t(sce)

begin_time <- Sys.time()
  
df <- nipals(data, center = TRUE, scale = F, ncomp = 40, 
             fitted = TRUE, verbose = TRUE)
  
end_time <- Sys.time()
  
time_difference <- end_time - begin_time
cat(time_difference)

saveRDS(object = df, file = paste0(here("Analyses/Leduc/Output_batch_effect_removal/"),"nipals_batch_removed_sce.RDS"))
saveRDS(object = time_difference, 
        file = paste0(here("Analyses/Leduc/Output_batch_effect_removal/"),"nipals_batch_removed_time.RDS"))

```


```{r}
set.seed(100)
for(i in c(1:10)){

  sce <- readRDS(paste0(here("Analyses","Leduc","Output_batch_effect_removal",
                                    paste0("logintensities_batch_removed_MISTOT10_MNAR25_", i, ".RDS"))))
  data <- t(sce[rowMeans(is.na(sce))<1,])
  
  
  
  df <- nipals(data, center = TRUE,  scale = F, ncomp = 40, 
               fitted = TRUE, verbose = TRUE)
    
  saveRDS(object = df, file = paste0(here("Analyses","Leduc","Output_batch_effect_removal"),"/nipals_batch_removed_MISTOT10_MNAR25_", i, ".RDS"))

}
```

```{r}
set.seed(100)

for(i in c(1:10)){

  sce <- readRDS(paste0(here("Analyses","Leduc","Output_batch_effect_removal",
                                    paste0("logintensities_batch_removed_MISTOT10_MNAR50_", i, ".RDS"))))
  data <- t(sce[rowMeans(is.na(sce))<1,])
  
  
  
  df <- nipals(data, center = TRUE, scale = F,  ncomp = 40, 
               fitted = TRUE, verbose = TRUE)
    
  saveRDS(object = df, file = paste0(here("Analyses","Leduc","Output_batch_effect_removal"),"/nipals_batch_removed_MISTOT10_MNAR50_", i, ".RDS"))

}
```


```{r}
set.seed(100)

for(i in c(1:10)){

  sce <- readRDS(paste0(here("Analyses","Leduc","Output_batch_effect_removal",
                                    paste0("logintensities_batch_removed_MISTOT10_MNAR75_", i, ".RDS"))))
  data <- t(sce[rowMeans(is.na(sce))<1,])
  
  
  
  df <- nipals(data, center = TRUE, scale = F,  ncomp = 40, 
               fitted = TRUE, verbose = TRUE)
    
  saveRDS(object = df, file = paste0(here("Analyses","Leduc","Output_batch_effect_removal"),"/nipals_batch_removed_MISTOT10_MNAR75_", i, ".RDS"))

}


```
