---
title: 'SGD CPTEx data'
author: "Alex"
date: "2024-07-18"
output: html_document
---


```{r}
library(here)
library(sgdGMF)
library(dplyr)
library(RSpectra)
library(scater)
library(BiocParallel)
library(BiocSingular)
library(DelayedArray)
library(fullRankMatrix)

devtools::load_all(here("omicsGMF"))

set.seed(100)
```



# Original data

```{r}
sce <- readRDS(file = here("Data","leduc2022_pSCoPE_data","leduc_sce.RDS"))

design <- model.matrix(~1+Channel+Set, data = colData(sce))
fmX <- make_full_rank_matrix(design)
X <- fmX$matrix

```


```{r}
begin_time <- Sys.time()
family <- gaussian()
sgd <-  calculateGMF(sce, X = X, 
                     family = family, exprs_values = "logintensities", 
                       control.alg = list(tol = 0.001, maxiter = 10000),
                       ncomponents = 10)
end_time <- Sys.time()
time_diff <- end_time - begin_time
print(time_diff)

```


```{r}
saveRDS(object = sgd, file = here("Analyses","Leduc","Output","sgd_batch_sce.RDS"))
saveRDS(time_diff, file = here("Analyses","Leduc","Output","sgd_batch_time.RDS"))
```


# Imputed missing data


```{r}
for(i in c(1:10)){
  MISTOT10_MNAR25 <- readRDS(paste0(here("Data","leduc2022_pSCoPE_data"),"/leduc_MISTOT10_MNAR25_", i, ".RDS"))
  MISTOT10_MNAR50 <- readRDS(paste0(here("Data","leduc2022_pSCoPE_data"),"/leduc_MISTOT10_MNAR50_", i, ".RDS"))
  MISTOT10_MNAR75 <- readRDS(paste0(here("Data","leduc2022_pSCoPE_data"),"/leduc_MISTOT10_MNAR75_", i, ".RDS"))


  assay(sce, "MISTOT10_MNAR25") <- MISTOT10_MNAR25$data
  sgd_10_25 <-  calculateGMF(sce, X = X, family = family, exprs_values = "MISTOT10_MNAR25", 
                             control.alg = list(tol = 0.001, maxiter = 10000),
                             ncomponents = 10)
  
  saveRDS(object = sgd_10_25, file = paste0(here("Analyses","Leduc","Output"),"/sgd_batch_MISTOT10_MNAR25_", i, ".RDS"))
  
  assay(sce, "MISTOT10_MNAR50") <- MISTOT10_MNAR50$data
  sgd_10_50 <-  calculateGMF(sce[rowMeans(is.na(MISTOT10_MNAR50$data))<1,], X = X, 
                             family = family, exprs_values = "MISTOT10_MNAR50", 
                             control.alg = list(tol = 0.001, maxiter = 10000),
                             ncomponents = 10)
  
  saveRDS(object = sgd_10_50, file = paste0(here("Analyses","Leduc","Output"),"/sgd_batch_MISTOT10_MNAR50_", i, ".RDS"))
  
  assay(sce, "MISTOT10_MNAR75") <- MISTOT10_MNAR75$data
  sgd_10_75 <-  calculateGMF(sce[rowMeans(is.na(MISTOT10_MNAR75$data))<1,], X = X, 
                             family = family, exprs_values = "MISTOT10_MNAR75", 
                             control.alg = list(tol = 0.001, maxiter = 10000),
                             ncomponents = 10)
  
  saveRDS(object = sgd_10_75, file = paste0(here("Analyses","Leduc","Output"),"/sgd_batch_MISTOT10_MNAR75_", i, ".RDS"))
  
  
  
}
```










