---
title: "CV CPTAC no lab1"
output: html_document
date: '2024-07-18'
---
# SGD GMF

```{r}
library(sgdGMF)
library(dplyr)
library(RSpectra)
library(scater)
library(BiocParallel)
library(BiocSingular)
library(here)
library(DelayedArray)

devtools::load_all(here("omicsGMF"))

```

# Load data
```{r}

# Read the original data that is already filtered, median normalized and preprocessed in /Data/CPTAC_nolab1/CPTAC_nolab1_data_preparation.Rmd.

sce <- readRDS(file = here("Data","CPTAC_nolab1","CPTAC_sce.RDS"))

# Define the condition and labs in colData to include as a known covariate in the GMF model
cond <- which(
  strsplit(colnames(sce)[[1]][1], split = "")[[1]] == "A") # find where condition is stored

colData(sce)$condition <- substr(colnames(sce), cond, cond) %>%
  unlist %>%  
  as.factor

colData(sce)$lab <- rep(rep(paste0("lab",2:3),each=3),5) %>% as.factor

# Both lab and condition are included as sample-level covariates.
X <- model.matrix(~1 + lab + condition, colData(sce))
```


## Cross validation
```{r}
set.seed(100)

family <- gaussian()
# Run the cross-validation to select the number of latent factors with lab and condition as known covariates.

cv <- calculateCVGMF(sce, family = family, X = X, 
                      exprs_values = "logintensities", ncomponents = seq(1,5,1), 
                      control.alg = list(tol = 0.001, maxiter = 10000), 
                      control.cv = list(nfolds = 3),
                      ntop = nrow(sce))

```

```{r}
saveRDS(object = cv, file = here("Analyses","CPTAC_nolab1","Output","crossval_batch_condition.RDS"))

```

```{r}
print(cv)
print(cv %>% group_by(ncomp) %>% summarise(mean_dev = mean(dev)))

```





