---
title: "Untitled"
output: html_document
date: "2025-07-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
```

```{r}
sce_CPTAC <- readRDS(file = here("Data/CPTAC_data/CPTAC_sce.RDS"))
sce_CPTAC_nolab1 <- readRDS(file = here("Data/CPTAC_nolab1/CPTAC_sce.RDS"))
sce_Petrosius <- readRDS(file = here("Data/Petrosius/petrosius_sce.RDS"))
sce_Leduc <- readRDS(file = here("Data/leduc2022_pSCoPE_data/leduc_sce.RDS"))

empca_CPTAC <- readRDS(file = paste0(here("Analyses/CPTAC/Output/empca_sce.RDS")))
empca_CPTAC_nolab1 <- 
  readRDS(file = paste0(here("Analyses/CPTAC_nolab1/Output/empca_sce.RDS")))
empca_Petrosius <- readRDS(file = paste0(here("Analyses/Petrosius/Output/empca_sce.RDS")))
empca_Leduc <- readRDS(file = paste0(here("Analyses/Leduc/Output/empca_sce.RDS")))

```

```{r}
CPTAC_PCs <- prcomp(empca_CPTAC$loadings %*% t(empca_CPTAC$scores), rank = 2)
CPTAC_nolab1_PCs <- prcomp(empca_CPTAC_nolab1$loadings %*%
                             t(empca_CPTAC_nolab1$scores), rank = 2)
Petrosius_PCs <- prcomp(empca_Petrosius$loadings %*% t(empca_Petrosius$scores), rank = 2)
Leduc_PCs <- prcomp(empca_Leduc$loadings %*% t(empca_Leduc$scores), rank = 2)

```


```{r}
lab <- rep(rep(paste0("lab",1:3),each=3),5) %>% as.factor
cond <- which(
  strsplit(colnames(sce_CPTAC)[[1]][1], split = "")[[1]] == "A") # find where condition is stored

colData(sce_CPTAC)$condition <- substr(colnames(sce_CPTAC), cond, cond) %>%
  unlist %>%  
  as.factor


lab_nolab1 <- rep(rep(paste0("lab",2:3),each=3),5) %>% as.factor
cond_nolab1 <- which(
  strsplit(colnames(sce_CPTAC_nolab1)[[1]][1], split = "")[[1]] == "A") # find where condition is stored

colData(sce_CPTAC_nolab1)$condition <- substr(colnames(sce_CPTAC_nolab1), cond_nolab1, cond_nolab1) %>%
  unlist %>%  
  as.factor



subcluster <- rep(NA, ncol(sce_Leduc))
subcluster[is.na(colData(sce_Leduc)$MelanomaSubCluster)] <- "Monocyte    "
subcluster[colData(sce_Leduc)$MelanomaSubCluster == "A"] <- "Melanoma A    "
subcluster[colData(sce_Leduc)$MelanomaSubCluster == "B"] <- "Melanoma B    "
subcluster <- as.factor(subcluster)

lcBatch <- factor(colData(sce_Leduc)$lcbatch, levels = c("A", "C"), labels = c("Batch 1", "Batch 2"))

```

```{r}
CPTAC_plot <- ggplot(data = CPTAC_PCs$x, 
         aes(x = PC1,y = PC2, col = colData(sce_CPTAC)$condition, shape = lab) ) +
    geom_point(size = 2.5) + xlab("PC1") + ggtitle("CPTAC") + 
    theme_bw() + labs(col = "Condition:") + scale_shape_manual(values=c("lab1" = 16,"lab2" = 17,"lab3" = 15)) + 
    theme(legend.text = element_text(size = 12), legend.title = element_text(size = 12), legend.position = "right") + 
    scale_colour_manual(name = "Condition:", 
                        values = c("A" = "#BC3C29FF", "B" = "#EFB118FF", "C" = "#3CA951FF",
                                   "D" = "#97BBF5FF", "E" = "#FF8AB7FF"))

CPTAC_nolab1_plot <- ggplot(data = CPTAC_nolab1_PCs$x, 
         aes(x = PC1,y = PC2, 
             col = colData(sce_CPTAC_nolab1)$condition, shape = lab_nolab1) ) +
    geom_point(size = 2.5) + xlab("PC1") + ggtitle("CPTAC no lab1") + 
    theme_bw() + labs(col = "Condition:") + scale_shape_manual(values=c("lab2" = 17,"lab3" = 15)) + 
    theme(legend.text = element_text(size = 12), legend.title = element_text(size = 12), legend.position = "right") + 
    scale_colour_manual(name = "Condition:", 
                        values = c("A" = "#BC3C29FF", "B" = "#EFB118FF", "C" = "#3CA951FF",
                                   "D" = "#97BBF5FF", "E" = "#FF8AB7FF"))

Petrosius_plot <- ggplot(data = Petrosius_PCs$x, 
       aes(x = PC1,y = PC2, color = as.factor(colData(sce_Petrosius)$SampleType))) +
  geom_point(alpha = 0.5) + scale_colour_manual(values = c("purple3","orange")) +
    xlab("PC1") + 
    ggtitle("Petrosius") + 
  theme_bw() + 
    labs(col = "Treatment:   ") + 
    theme(legend.text = element_text(size = 12), legend.title = element_text(size = 12),
          legend.position = "right") + guides(color = guide_legend(override.aes = list(alpha = 1))) 


Leduc_plot <- ggplot(data = Leduc_PCs$x, 
       aes(x = PC1,y = PC2, col = subcluster, shape = lcBatch)) +
  geom_point(alpha = 0.5) + xlab("PC1") + ggtitle("Leduc") + 
  theme_bw() + labs(col = "Celltype:   ", shape = "LC-batch:   ") + 
    theme(legend.text = element_text(size = 12), legend.title = element_text(size = 12),
          legend.position = "right", legend.box="vertical") + 
    scale_colour_manual(name = "Cell type:   ", 
                        values = c("Monocyte    " = "#4269D0FF", "Melanoma A    " = "#E18727FF", "Melanoma B    " = "#20854EFF")) + 
   guides(nrow = 2, 
    colour = guide_legend(order = 1, override.aes = list(alpha = 1)), 
    shape = guide_legend(order = 2, override.aes = list(alpha = 1, colour = "black"))
  )

legend_CPTAC <- as_ggplot(get_legend(CPTAC_plot))
legend_Petrosius <- as_ggplot(get_legend(Petrosius_plot))
legend_Leduc <- as_ggplot(get_legend(Leduc_plot))

```

```{r}
combined_plot <- ggpubr::ggarrange(
  ggpubr::ggarrange(
                                   Petrosius_plot + theme(legend.position = "none"),
                                   Leduc_plot + theme(legend.position = "none"),
                                   CPTAC_plot + theme(legend.position = "none"), 
                                   CPTAC_nolab1_plot + theme(legend.position = "none"), 
                        ncol = 1, nrow = 4, align = "h", common.legend = F, labels = "AUTO"),
  ggpubr::ggarrange(
                    as_ggplot(get_legend(Petrosius_plot + labs(col = "Treatment") + 
                                     theme(legend.text = element_text(size = 12), legend.title = element_text(size = 12),
                                           legend.key.size = unit(0.2, "cm"), legend.margin = margin(0, 0, 0, 0), legend.justification = "left", 
                                           legend.box.margin =  margin(l = 1, unit = "cm")))),
                    as_ggplot(get_legend(Leduc_plot + labs(col = "Celltype") + 
                                     theme(legend.text = element_text(size = 12), legend.title = element_text(size = 12),
                                           legend.key.size = unit(0.2, "cm"), legend.margin = margin(0, 0, 0, 0), legend.justification = "left", 
                                           legend.box.margin =  margin(l = 1, unit = "cm")))),
                    as_ggplot(get_legend(CPTAC_plot + 
                                     theme(legend.text = element_text(size = 12), legend.title = element_text(size = 12),
                                           legend.key.size = unit(0.2, "cm"), legend.margin = margin(0, 0, 0, 0), legend.justification = "left", 
                                           legend.box.margin =  margin(l = 1, unit = "cm")))), 
                    ncol = 1, nrow = 3, align = "h", common.legend = F,  heights = c(0.25, 0.25, 0.5)),
  widths = c(0.75, 0.25)
)


ggsave(plot = combined_plot, filename = here("Figures/visualizations_empca.pdf"), device = "pdf", dpi = 500, units = "mm", width = 180, height = 215)

```


```{r}
library(openxlsx)

excel_supp_fig_13 <- rbind(Petrosius_plot$data %>% 
                             as.data.frame() %>% 
                             mutate(col = colData(sce_Petrosius)$SampleType, shape = NA),
                           Leduc_plot$data %>% 
                             as.data.frame() %>% 
                             mutate(col = subcluster, shape = lcBatch),
                           CPTAC_plot$data %>% 
                             as.data.frame() %>% 
                             mutate(col = colData(sce_CPTAC)$condition, shape = lab),
                           CPTAC_nolab1_plot$data %>% 
                             as.data.frame() %>% 
                             mutate(col = colData(sce_CPTAC_nolab1)$condition, shape = lab_nolab1)
                           )


file_path <- here("Figures/Source_Data.xlsx")

# Load existing workbook
wb <- loadWorkbook(file_path)

# Add new worksheet
addWorksheet(wb, "Supp_fig_13")

# Write data
writeData(wb, "Supp_fig_13", excel_supp_fig_13)

# Save
saveWorkbook(wb, file_path, overwrite = TRUE)

```


