---
title: "sgdGMF CPTEx"
output: html_document
date: '2024-07-18'
---
# SGD GMF

```{r}
library(sgdGMF)
library(dplyr)
library(RSpectra)
library(scater)
library(BiocParallel)
library(BiocSingular)
library(DelayedArray)
library(here)

devtools::load_all(here("omicsGMF"))

```

# Load data
```{r}
# Read the original data that is already filtered, median normalized and preprocessed in /Data/CPTAC_data.Rmd.
sce <- readRDS(file = here("Data","CPTAC_data","CPTAC_sce.RDS"))

# Define the condition and labs in colData to include as a known covariate in the GMF model

cond <- which(
  strsplit(colnames(sce)[[1]][1], split = "")[[1]] == "A") # find where condition is stored

colData(sce)$condition <- substr(colnames(sce), cond, cond) %>%
  unlist %>%  
  as.factor

colData(sce)$lab <- rep(rep(paste0("lab",1:3),each=3),5) %>% as.factor

# Only lab is included as a known sample-level covariate
X <- model.matrix(~1+lab, colData(sce))

# Here, protein is included as a known feature-level covariate
design_feature <- model.matrix(~1+Proteins, data = rowData(sce))
Z <- design_feature

```


## Cross validation
```{r}
set.seed(100)

family <- gaussian()

# Run the cross-validation to select the number of latent factors with lab and protein as known covariates.
cv <- calculateCVGMF(sce, family = family, X = X, Z = Z, 
                      exprs_values = "logintensities", ncomponents = seq(1,10,1), 
                      control.alg = list(tol = 0.001, maxiter = 10000), 
                      control.cv = list(nfolds = 3),
                      ntop = nrow(sce))

```

```{r}
saveRDS(object = cv, file = here("Analyses","CPTAC","Output","crossval_batch_proteins.RDS"))

```

```{r}
print(cv)
print(cv %>% group_by(ncomp) %>% summarise(mean_dev = mean(dev)))

```





