---
title: "Untitled"
output: html_document
date: '2024-07-18'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(here)
library(scran)

devtools::load_all(here("omicsGMF"))

```

```{r}
# Function to calculate the mean average error calculation between the original
# value and its imputed value after it has been put to a missing value.
MAE_calculation <- function(imputed, original){
  mean(abs(imputed-original))
}

# Function to impute missing values with nipals.
reconstruct_nipals <- function(nipals){
  
  reconstructed <- nipals$fitted
  
  return(reconstructed)
}

# Define the different labs as the following imputations are evaluated only 
# for lab1 for Supplementary materials.

lab <- rep(rep(paste0("lab",1:3),each=3),5) %>% as.factor

```


# imputation errors

```{r}

df_all <- data.frame("MNAR" = NULL,
                     "MAE" = NULL,
                     "method" = NULL)

# loop over the simulations with 25, 50, and 75 percent of the introduced missing values 
# being due to low abundance. This is done for 10 different simulations.
for(i in c("25", "50", "75")){
  for(j in c(1:10)){
# Read the original data that is already filtered, median normalized and preprocessed in /Data/CPTAC_data.Rmd.
    
  original <- readRDS(file =  here("Data","CPTAC_data", "CPTAC_sce.RDS"))
  
  # Read the files that contain the information of the simulation, such as which values
  # were put to missing due to MCAR and MNAR in the specific simulation. 

  NAs <- readRDS(file  =  here("Data","CPTAC_data", paste0("CPTAC_MISTOT10_MNAR", i, "_", j, ".RDS")))
  
  # Rows that have all missing values were removed as in these cases no imputation can be done
  original <- original[rowMeans(is.na(NAs$data)) < 1 ,]
  
  # Read in the imputation results for the different methods for that specific simulation setting.
    # GMF model without covariates

  sgd <- readRDS(file = here("Analyses","CPTAC", "Output", 
                             paste0("sgd_MISTOT10_MNAR", i, "_", j, ".RDS")))
  
    # GMF model with 2 fixed effects for lab.

  sgd_batch <- readRDS(file = here("Analyses","CPTAC", "Output", 
                             paste0("sgd_batch_MISTOT10_MNAR", i, "_", j, ".RDS")))
  
      # GMF model with 2 fixed effects for lab and 4 fixed effects for condition.

  sgd_batch_condition <- readRDS(file = here("Analyses","CPTAC", "Output", 
                             paste0("sgd_batch_condition_MISTOT10_MNAR", i, "_", j, ".RDS")))

 # impute the missing values with the GMF models
  
  sgd_reconstructed <- t(imputeGMF(NAs$data[rowMeans(is.na(NAs$data)) < 1 ,], sgd))
  sgd_batch_reconstructed <- t(imputeGMF(NAs$data[rowMeans(is.na(NAs$data)) < 1 ,], sgd_batch))
  sgd_batch_condition_reconstructed <- t(imputeGMF(NAs$data[rowMeans(is.na(NAs$data)) < 1 ,], sgd_batch_condition))

  
# Load the other imputation results.
 DAE <- as.matrix(data.table::fread(file = here("Analyses","CPTAC", "Output", 
                              paste0("DAE_MISTOT10_MNAR", i, "_", j,".csv")),
                  header = "auto"), rownames = 1)
  DAE_default <- as.matrix(data.table::fread(file = here("Analyses","CPTAC", "Output", 
                              paste0("DAE_default_MISTOT10_MNAR", i, "_", j,".csv")),
                  header = "auto"), rownames = 1)
  
  CF <- as.matrix(data.table::fread(file = here("Analyses","CPTAC", "Output", 
                              paste0("CF_MISTOT10_MNAR", i, "_", j,".csv")),
                  header = "auto"), rownames = 1)
  CF_default <- as.matrix(data.table::fread(file = here("Analyses","CPTAC", "Output", 
                              paste0("CF_default_MISTOT10_MNAR", i, "_", j,".csv")),
                  header = "auto"), rownames = 1)
  
  VAE <- as.matrix(data.table::fread(file = here("Analyses","CPTAC", "Output", 
                              paste0("VAE_MISTOT10_MNAR", i, "_", j,".csv")),
                  header = "auto"), rownames = 1)
  VAE_default <- as.matrix(data.table::fread(file = here("Analyses","CPTAC", "Output", 
                              paste0("VAE_default_MISTOT10_MNAR", i, "_", j,".csv")),
                  header = "auto"), rownames = 1)
  
    nipals <- readRDS(file = here("Analyses","CPTAC", "Output",
                              paste0("nipals_MISTOT10_MNAR", i, "_", j, ".RDS")))
  nipals_reconstructed <- reconstruct_nipals(nipals)
    
  knn <- readRDS(file = here("Analyses","CPTAC", "Output", 
                              paste0("knnmethod_MISTOT10_MNAR", i, "_", j, ".RDS")))
  qrilc <- readRDS(file = here("Analyses","CPTAC", "Output", 
                              paste0("qrilc_MISTOT10_MNAR", i, "_", j, ".RDS")))
  zero <- readRDS(file = here("Analyses","CPTAC", "Output", 
                              paste0("zero_MISTOT10_MNAR", i, "_", j, ".RDS")))
  minimum <- readRDS(file = here("Analyses","CPTAC", "Output",  
                              paste0("minimum_MISTOT10_MNAR", i, "_", j, ".RDS")))
  
  
  # define three classes of results: considering all outliers, considering outliers
  # that were simulated ad random, and outliers that were simulated due to low abundance
  imputed_all <- t((NAs$MAR + NAs$MNAR)[rowMeans(is.na(NAs$data)) < 1 ,] == 1)
  imputed_MAR <- t(NAs$MAR[rowMeans(is.na(NAs$data)) < 1 ,] == 1)
  imputed_MNAR <- t(NAs$MNAR[rowMeans(is.na(NAs$data)) < 1 ,] == 1)

  
  # combine all imputations
  methods <- list(sgd_reconstructed, 
                  sgd_batch_reconstructed, 
                  sgd_batch_condition_reconstructed, 
                  DAE, CF, VAE,
                  DAE_default, CF_default, VAE_default, 
                  nipals_reconstructed, knn, qrilc, zero, minimum)
  methods_names <- c("SGD", 
                     "SGD Batch", 
                     "SGD Batch condition", 
                     "DAE-NN", "CF-NN", "VAE-NN",
                     "DAE-default-NN", "CF-default-NN", "VAE-default-NN",
                     "NIPALS", "KNN", "QRILC","zero","minimum")
  
  # Compute the MAE for all methods for only lab1
  MAE_all <- sapply(methods, FUN = function(x){
    MAE_calculation(imputed = x[imputed_all & lab == "lab1"], 
                    original = t(assay(original, "logintensities"))[imputed_all & lab == "lab1"])
  })
  


  MAE_MAR <- sapply(methods, FUN = function(x){
  MAE_calculation(imputed = x[imputed_MAR & lab == "lab1"],
                  original = t(assay(original, "logintensities"))[imputed_MAR & lab == "lab1"])
  })
  



  MAE_MNAR <- sapply(methods, FUN = function(x){
  MAE_calculation(imputed = x[imputed_MNAR & lab == "lab1"], 
                  original = t(assay(original, "logintensities"))[imputed_MNAR & lab == "lab1"])
  })

 
  # Combine results for all simulations
  
  df_loop <- data.frame(
                     "MNAR" = i,
                     "MAE" = c(MAE_all, 
                               MAE_MNAR, 
                               MAE_MAR), 
                     "method" = rep(c(methods_names), times = 3), 
                     "missing_type" = rep(c("all","MNAR","MAR"), 
                                          each = length(MAE_all)))
  
  
  df_all <- rbind(df_all, df_loop)
}

}

df_all$MNAR <- factor(df_all$MNAR, levels = c("25","50","75"))
df_all$method <- factor(df_all$method, 
                        levels = c("SGD", 
                     "SGD Batch",
                     "SGD Batch condition", 
                     "DAE-NN", "CF-NN", "VAE-NN",
                     "DAE-default-NN", "CF-default-NN", "VAE-default-NN",
                     "NIPALS", "KNN", "QRILC","zero","minimum"))


saveRDS(object = df_all, file = here("Analyses/CPTAC/Output/imputation_results_CPTAC_lab1.RDS"))
```
