---
title: "NAguideR analyses"
output: html_document
date: '2024-07-18'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(SummarizedExperiment)
library(SingleCellExperiment)
library(scater)
library(scran)
source(here("R-functions","NAguideR_functions.R"))
```


# All data

```{r}

set.seed(100)

# Read the original data that is already filtered, median normalized and preprocessed in /Data/CPTAC_data.Rmd.
sce <- readRDS(file = here("Data/CPTAC_data/CPTAC_sce.RDS"))
data <- t(assay(sce, "logintensities"))

# Considering zero, minimum, KNN and QRILC imputation
methods <- c("zero", "minimum", "knnmethod", "qrilc")

# Impute missing values with the different methods.
for(i in methods){
  
  begin_time <- Sys.time()
  
  df <- nafunctions(x = data, method = i)
  
  end_time <- Sys.time()
  
  time_difference <- end_time - begin_time
  
  saveRDS(object = df, file = paste0(here("Analyses/CPTAC/Output/"),i, "_sce.RDS"))
  saveRDS(object = time_difference, file = paste0(here("Analyses/CPTAC/Output/"),i, "_time.RDS"))

  }


```





```{r}
set.seed(100)

# Impute missing values with the different methods for the different simulations in which
# 25% of the simulated missing values are missing due to low abundance.

for (j in c(1:10)){
  sce <- readRDS(file = paste0(here("Data/CPTAC_data"), "/CPTAC_MISTOT10_MNAR25_", j, ".RDS"))
  
  # Filter rows with all missing values in a row
  data <- t(sce$data[rowMeans(is.na(sce$data))<1,])

methods <- c("zero", "minimum", "knnmethod", "qrilc")

  for(i in methods){
    if(!file.exists(paste0(here("Analyses/CPTAC/Output/"),i, "_MISTOT10_MNAR25_", j, ".RDS"))){
      
      df <- nafunctions(x = data, method = i)
      
      saveRDS(object = df, file = paste0(here("Analyses/CPTAC/Output/"),i, "_MISTOT10_MNAR25_", j, ".RDS"))
      
    }
  }
}

```



```{r}
set.seed(100)

# Impute missing values with the different methods for the different simulations in which
# 50% of the simulated missing values are missing due to low abundance.

for (j in c(1:10)){
  sce <- readRDS(file = paste0(here("Data/CPTAC_data"), "/CPTAC_MISTOT10_MNAR50_", j, ".RDS"))
  
    # Filter rows with all missing values in a row
  data <- t(sce$data[rowMeans(is.na(sce$data))<1,])

methods <- c("zero", "minimum", "knnmethod", "qrilc")

  for(i in methods){
    if(!file.exists(paste0(here("Analyses/CPTAC/Output/"),i, "_MISTOT10_MNAR50_", j, ".RDS"))){
      
      df <- nafunctions(x = data, method = i)
      
      saveRDS(object = df, file = paste0(here("Analyses/CPTAC/Output/"),i, "_MISTOT10_MNAR50_", j, ".RDS"))
      
    }
  }
}

```



```{r}
set.seed(100)

# Impute missing values with the different methods for the different simulations in which
# 75% of the simulated missing values are missing due to low abundance.

for (j in c(1:10)){
  sce <- readRDS(file = paste0(here("Data/CPTAC_data"), "/CPTAC_MISTOT10_MNAR75_", j, ".RDS"))
  
  # Filter rows with all missing values in a row
  data <- t(sce$data[rowMeans(is.na(sce$data))<1,])

methods <- c("zero", "minimum", "knnmethod", "qrilc")

  for(i in methods){
    if(!file.exists(paste0(here("Analyses/CPTAC/Output/"),i, "_MISTOT10_MNAR75_", j, ".RDS"))){
      
      df <- nafunctions(x = data, method = i)
      
      saveRDS(object = df, file = paste0(here("Analyses/CPTAC/Output/"),i, "_MISTOT10_MNAR75_", j, ".RDS"))
      
    }
  }
}

```
