---
title: "Untitled"
output: html_document
date: '2024-07-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(nipals)
library(here)
library(scran)
library(SummarizedExperiment)
library(SingleCellExperiment)
```

```{r}
set.seed(100)
# Read the original data that is already filtered, median normalized and preprocessed in /Data/CPTAC_data.Rmd.

sce <- readRDS(file = here("Data/CPTAC_data/CPTAC_sce.RDS"))
data <- t(assay(sce, "logintensities"))

begin_time <- Sys.time()
  
# run NIPALS pca
df <- nipals(data, center = TRUE, scale = F, ncomp = 6, 
             fitted = TRUE, verbose = TRUE)
  
end_time <- Sys.time()
  
time_difference <- end_time - begin_time
cat(time_difference)

saveRDS(object = df, file = paste0(here("Analyses/CPTAC/Output/"),"nipals_sce.RDS"))
saveRDS(object = time_difference, 
        file = paste0(here("Analyses/CPTAC/Output/"),"nipals_time.RDS"))

```

```{r}
set.seed(100)

# Run NIPALS pca for the different simulations in which
# 25% of the simulated missing values are missing due to low abundance.

for(i in c(1:10)){

  sce <- readRDS(paste0(here("Data","CPTAC_data"),"/CPTAC_MISTOT10_MNAR25_", i, ".RDS"))
  data <- t(sce$data[rowMeans(is.na(sce$data))<1,])
  
  
  
  df <- nipals(data, center = TRUE,  scale = F, ncomp = 6, 
               fitted = TRUE, verbose = TRUE)
    
  saveRDS(object = df, file = paste0(here("Analyses","CPTAC","Output"),"/nipals_MISTOT10_MNAR25_", i, ".RDS"))

}
```

```{r}
set.seed(100)

# Run NIPALS pca for the different simulations in which
# 50% of the simulated missing values are missing due to low abundance.

for(i in c(1:10)){

  sce <- readRDS(paste0(here("Data","CPTAC_data"),"/CPTAC_MISTOT10_MNAR50_", i, ".RDS"))
  data <- t(sce$data[rowMeans(is.na(sce$data))<1,])
  
  
  
  df <- nipals(data, center = TRUE, scale = F,  ncomp = 6, 
               fitted = TRUE, verbose = TRUE)
    
  saveRDS(object = df, file = paste0(here("Analyses","CPTAC","Output"),"/nipals_MISTOT10_MNAR50_", i, ".RDS"))

}
```


```{r}
set.seed(100)

# Run NIPALS pca for the different simulations in which
# 75% of the simulated missing values are missing due to low abundance.

for(i in c(1:10)){

  sce <- readRDS(paste0(here("Data","CPTAC_data"),"/CPTAC_MISTOT10_MNAR75_", i, ".RDS"))
  data <- t(sce$data[rowMeans(is.na(sce$data))<1,])
  
  
  
  df <- nipals(data, center = TRUE, scale = F,  ncomp = 6, 
               fitted = TRUE, verbose = TRUE)
    
  saveRDS(object = df, file = paste0(here("Analyses","CPTAC","Output"),"/nipals_MISTOT10_MNAR75_", i, ".RDS"))

}


```


