---
title: 'SGD CPTAC data'
author: "Alex"
date: "2024-07-18"
output: html_document
---


```{r}
library(here)
library(sgdGMF)
library(dplyr)
library(RSpectra)
library(scater)
library(BiocParallel)
library(BiocSingular)
library(DelayedArray)

devtools::load_all(here("omicsGMF"))

set.seed(100)
```



# Original data

```{r}
# Read the original data that is already filtered, median normalized and preprocessed in /Data/CPTAC_data.Rmd.

sce <- readRDS(file = here("Data","CPTAC_data","CPTAC_sce.RDS"))

```


```{r}
begin_time <- Sys.time()
family <- gaussian()

#Run GMF on the original data that is filtered, median normalized and preprocessed in /Data/CPTAC_data.Rmd.
sgd <-  calculateGMF(sce, family = family, exprs_values = "logintensities", 
                       control.alg = list(tol = 0.001, maxiter = 10000),
                       ncomponents = 6)
end_time <- Sys.time()
time_diff <- end_time - begin_time
print(time_diff)

```


```{r}
saveRDS(object = sgd, file = here("Analyses","CPTAC","Output","sgd_sce.RDS"))
saveRDS(time_diff, file = here("Analyses","CPTAC","Output","sgd_time.RDS"))
```


# simulated missing data


```{r}

# Run GMF for the different simulations in which
# 25, 50 and 75% of the simulated missing values are missing due to low abundance.


for(i in c(1:10)){
  MISTOT10_MNAR25 <- readRDS(paste0(here("Data","CPTAC_data"),"/CPTAC_MISTOT10_MNAR25_", i, ".RDS"))
  MISTOT10_MNAR50 <- readRDS(paste0(here("Data","CPTAC_data"),"/CPTAC_MISTOT10_MNAR50_", i, ".RDS"))
  MISTOT10_MNAR75 <- readRDS(paste0(here("Data","CPTAC_data"),"/CPTAC_MISTOT10_MNAR75_", i, ".RDS"))

  
  assay(sce, "MISTOT10_MNAR25") <- MISTOT10_MNAR25$data
  sgd_10_25 <-  calculateGMF(sce, family = family, exprs_values = "MISTOT10_MNAR25", 
                             control.alg = list(tol = 0.001, maxiter = 10000),
                             ncomponents = 6)
  
  saveRDS(object = sgd_10_25, file = paste0(here("Analyses","CPTAC","Output"),"/sgd_MISTOT10_MNAR25_", i, ".RDS"))
  
  assay(sce, "MISTOT10_MNAR50") <- MISTOT10_MNAR50$data
  sgd_10_50 <-  calculateGMF(sce[rowMeans(is.na(MISTOT10_MNAR50$data))<1,],
                             family = family, exprs_values = "MISTOT10_MNAR50", 
                             control.alg = list(tol = 0.001, maxiter = 10000),
                             ncomponents = 6)
  
  saveRDS(object = sgd_10_50, file = paste0(here("Analyses","CPTAC","Output"),"/sgd_MISTOT10_MNAR50_", i, ".RDS"))
  
  assay(sce, "MISTOT10_MNAR75") <- MISTOT10_MNAR75$data
  sgd_10_75 <-  calculateGMF(sce[rowMeans(is.na(MISTOT10_MNAR75$data))<1,], 
                             family = family, exprs_values = "MISTOT10_MNAR75", 
                             control.alg = list(tol = 0.001, maxiter = 10000),
                             ncomponents = 6)
  
  saveRDS(object = sgd_10_75, file = paste0(here("Analyses","CPTAC","Output"),"/sgd_MISTOT10_MNAR75_", i, ".RDS"))
  

}
```







