---
title: 'NAguideR simulated data'
author: "Alex"
date: "2024-07-18"
output: html_document
---


```{r}
library(here)
library(sgdGMF)
library(dplyr)
library(RSpectra)
library(scater)
library(BiocParallel)
library(BiocSingular)
library(DelayedArray)

source(here("R-functions","NAguideR_functions.R"))
devtools::load_all(here("omicsGMF"))

```


```{r}
family <- gaussian()
fixed_feature <- 5000
fixed_sample <- 1000
fixed_dim <- 10
```


# Sample benchmarks

```{r}
methods <- c("zero", "minimum", "knnmethod", "qrilc")
for(i in methods){
  for(sample_size in c(100, 1000, 10000, 100000)){
    if(!file.exists(here("Analyses","Computational_time_benchmark","Output",
                         paste0(i, "_analysis_", fixed_feature, 
                                "_features_", sample_size, "_samples.RDS"))
    )){
      set.seed(100)
      values <- readRDS(
        file = here(paste0("Data/Computational_time_benchmark/simulated_", fixed_feature, 
                           "_features_", sample_size, "_samples.RDS")))
      begin_time <- Sys.time()
      analysis <- nafunctions(x = t(values), method = i)
      end_time <- Sys.time()
      time_diff <- end_time - begin_time
      saveRDS(object = time_diff, 
              file = here("Analyses","Computational_time_benchmark","Output",
                          paste0(i, "_time_", fixed_feature, 
                                 "_features_", sample_size, "_samples.RDS")))
      saveRDS(object = analysis, 
              file = here("Analyses","Computational_time_benchmark","Output",
                          paste0(i, "_analysis_", fixed_feature, 
                                 "_features_", sample_size, "_samples.RDS")))
      
      rm(analysis)
      gc()
    }
    
  }
  
}
```
