---
title: 'SGD CPTEx data'
author: "Alex"
date: "2024-07-18"
output: html_document
---


```{r}
library(here)
library(sgdGMF)
library(dplyr)
library(RSpectra)
library(scater)
library(BiocParallel)
library(BiocSingular)
library(DelayedArray)

devtools::load_all(here("omicsGMF"))

```


```{r}
family <- gaussian()
fixed_feature <- 5000
fixed_sample <- 1000
fixed_dim <- 10
```


# Dimensions benchmarks
```{r}
for(dim in c(5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)){
  if(!file.exists(here("Analyses","Computational_time_benchmark","Output",
                                            paste0("sgd_analysis_", fixed_feature, 
                      "_features_", fixed_sample, "_samples_", dim, ".RDS"))
                 )){
  set.seed(100)
  values <- readRDS(
          file = here(paste0("Data/Computational_time_benchmark/simulated_", fixed_feature, 
                      "_features_", fixed_sample, "_samples.RDS")))
  begin_time <- Sys.time()
  analysis <- calculateGMF(values, family = family, 
                             control.alg = list(tol = 0.001, maxiter = 10000),
                             ncomponents = dim)
  end_time <- Sys.time()
  time_diff <- end_time - begin_time
    saveRDS(object = time_diff, 
            file = here("Analyses","Computational_time_benchmark","Output",
                                            paste0("sgd_time_", fixed_feature, 
                      "_features_", fixed_sample, "_samples_", dim, ".RDS")))
    saveRDS(object = analysis, 
            file = here("Analyses","Computational_time_benchmark","Output",
                                            paste0("sgd_analysis_", fixed_feature, 
                      "_features_", fixed_sample, "_samples_", dim, ".RDS")))
    rm(analysis)
    gc()
  }

}
```



